### ISSUE TITLE
disableLocalStorage:true throwing ambiguous error

### ISSUE THREAD

**Issue by nandanrao** [payloadcms/plugin-cloud-storage#10]
Hi Payload, 

Not sure where to put this, it seems this is a problem with core `payload`, but it seems to only apply here. When trying to get a basic example of this working, I ran into an error that seems to be related to `disableLocalFileStorage`. 

When I run a basic example of this adapter, everything works with `disableLocalStorage: false`. But when I set it to true (or leave it as default), I get the following error. It also happens even without this plugin, whenever I try to set `disableLocalStorage: true`. 

```shell
TypeError: Cannot read properties of undefined (reading 'split')
    at getOutputImage (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/uploads/imageResizer.ts:29:33)
    at /Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/uploads/imageResizer.ts:65:27
    at async Promise.all (index 0)
    at resizeAndSave (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/uploads/imageResizer.ts:88:22)
    at uploadFile (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/uploads/uploadFile.ts:100:30)
    at update (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/collections/operations/update.ts:131:10)
    at updateHandler (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/collections/requestHandlers/update.ts:23:17)
[18:40:32] ERROR (payload): FileUploadError: There was a problem while uploading the file.
    at new ExtendableError (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/errors/APIError.ts:26:11)
    at new APIError (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/errors/APIError.ts:43:5)
    at new FileUploadError (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/errors/FileUploadError.ts:6:5)
    at uploadFile (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/uploads/uploadFile.ts:113:15)
    at update (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/collections/operations/update.ts:131:10)
    at updateHandler (/Users/nandanrao/Documents/payload/kannact-web/node_modules/payload/src/collections/requestHandlers/update.ts:23:17)
```

My collection is as follows: 

```
const Examples: CollectionConfig = {
  slug: "examples",
  admin: {
    useAsTitle: "someField",
  },
  upload: {
    disableLocalStorage: true, // this line can be removed and let the plugin set it to true, same behavior. 
    imageSizes: [
      {
        name: "thumbnail",
        width: 400,
        height: 300,
        position: "centre",
      },
    ],
    adminThumbnail: "thumbnail",
    mimeTypes: ["image/*"],
  },
  fields: [
    {
      name: "someField",
      type: "text",
    },
  ],
};
```

The workaround is simply to set `disableLocalStorage: false` in the adapter and remove all local paths in the `upload` config and then everything works as expected.

**Comment by denolfe** [comment]
Hey @nandanrao , thank you for the report. What version of payload core are you seeing this behavior on?

**Comment by nandanrao** [comment]
Right, sorry: 1.1.1

**Comment by DanRibbens** [comment]
Hey @nandanrao, 
We had some file upload issues in Payload 1.1.1, can you update to 1.1.2 and report back?

**Comment by nandanrao** [comment]
Yep, that solved it, thanks!
