### ISSUE TITLE
Error while adding this plugin to payload

### ISSUE THREAD

**Issue by SyedMuzamilM** [payloadcms/plugin-cloud-storage#14]
`TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:562:9)
    at new URL (node:internal/url:642:5)
    at parseUrl (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@aws-sdk/url-parser/dist-cjs/index.js:7:38)
    at resolveEndpointsConfig (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@aws-sdk/config-resolver/dist-cjs/endpointsConfig/resolveEndpointsConfig.js:14:87)
    at new S3Client (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:22:72)
    at new S3 (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@aws-sdk/client-s3/dist-cjs/S3.js:98:1)
    at Object.adapter (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@payloadcms/plugin-cloud-storage/src/adapters/s3/index.ts:18:16)
    at /home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@payloadcms/plugin-cloud-storage/src/plugin.ts:34:35
    at Array.map (<anonymous>)
    at /home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/@payloadcms/plugin-cloud-storage/src/plugin.ts:30:47
    at /home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/config/build.ts:14:34
    at Array.reduce (<anonymous>)
    at buildConfig (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/config/build.ts:13:46)
    at Object.<anonymous> (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/src/payload.config.ts:29:27)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module._compile (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/pirates/lib/index.js:136:24)
    at Module.m._compile (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at require.extensions.<computed> (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/index.ts:1059:12)
    at Object.newLoader [as .ts] (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfig (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/config/load.ts:37:16)
    at init (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/init.ts:57:30)
    at initSync (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/init.ts:150:7)
    at Payload.init (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/payload/src/index.ts:125:13)
    at Object.<anonymous> (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/src/server.ts:13:9)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Module.m._compile (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Object.require.extensions.<computed> (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at main (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/home/syedmuzamil/projects/work_projects/BeFinSavvy/wealthup-cms/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47`

I am getting this error when i tried to use this plugin with payload
And I am not able to figure out this issue

**Comment by denolfe** [comment]
@SyedMuzamilM We'd need a bit more information to troubleshoot. Can you please provide some information on how you're configuring it within your Payload config?

**Comment by SyedMuzamilM** [comment]
I followed the guidelines from the README. But I think the endpoint url might have been wrong.
Can you tell me the proper env variables value.
