### ISSUE TITLE
Can't use gcsAdapter with credentials inside private .env

### ISSUE THREAD

**Issue by arieltonglet** [payloadcms/plugin-cloud-storage#17]
Hello!
First of all, thanks a lot for this plugin. It's a huge help to deal with this kind of stuff :)
I'm trying to use it with Google Cloud Storage adapter, but I can only make it work if I paste the credentials **directly** inside the adapter.

Example repo:
https://github.com/arieltonglet/payload-gcs-credentials-test

What I've tried so far:

**Inserting credentials directly as object literal inside options**
Like this:
```
adapter: gcsAdapter({
    options: {
        credentials: {
            type: "service_account",
            private_key: "-----BEGIN PRIVATE KEY-----\nxxxxxxxxxx\n-----END PRIVATE KEY-----\n",
            client_email: "xxxxxxxxxx@xxxxxxxxxx.iam.gserviceaccount.com",
            client_id: "xxxxxxxxxx",
        },
    },
    bucket: "xxxxxxxxxx",
}),
```

Worked, but it's not secure, as the credentials would be exposed

**Loading credentials JSON file, using "keyFilename" prop**
Worked, but the same security issues form last try applies

**Adding a "credentials" object literal that loads its props via .env vars**
Like this:
```
adapter: gcsAdapter({
    options: {
      credentials: {
        type: "service_account",
        private_key: process.env.GCS_PRIVATE_KEY,
        client_email: process.env.GCS_CLIENT_EMAIL,
        client_id: process.env.GCS_CLIENT_ID,
      },
    },
    bucket: process.env.GCS_BUCKET,
}),
```

Files already uploaded now are broken in gallery.
Error in payload console when I try to upload:
```
[14:30:43] ERROR (payload): There was an error while uploading files corresponding to the collection media with filename 738-1920x1080.jpg:
[14:30:43] ERROR (payload): error:0909006C:PEM routines:get_name:no start line
    Error: error:0909006C:PEM routines:get_name:no start line
        at Sign.sign (node:internal/crypto/sig:131:29)
        at Object.sign ([...]/payload-gcs-credentials-test/node_modules/jwa/index.js:152:45)
        at Object.jwsSign [as sign] ([...]/payload-gcs-credentials-test/node_modules/jws/lib/sign-stream.js:32:24)
        at GoogleToken.requestToken ([...]/payload-gcs-credentials-test/node_modules/gtoken/build/src/index.js:232:31)
        at GoogleToken.getTokenAsyncInner ([...]/payload-gcs-credentials-test/node_modules/gtoken/build/src/index.js:166:21)
        at GoogleToken.getTokenAsync ([...]/payload-gcs-credentials-test/node_modules/gtoken/build/src/index.js:145:55)
        at GoogleToken.getToken ([...]/payload-gcs-credentials-test/node_modules/gtoken/build/src/index.js:97:21)
        at JWT.refreshTokenNoCache ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/jwtclient.js:172:36)
        at JWT.refreshToken ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/oauth2client.js:153:24)
        at JWT.getRequestMetadataAsync ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/oauth2client.js:298:28)
        at JWT.getRequestMetadataAsync ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/jwtclient.js:94:26)
        at JWT.requestAsync ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/oauth2client.js:371:34)
        at JWT.request ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/oauth2client.js:365:25)
        at GoogleAuth.request ([...]/payload-gcs-credentials-test/node_modules/google-auth-library/build/src/auth/googleauth.js:689:23)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at Upload.makeRequest ([...]/payload-gcs-credentials-test/node_modules/@google-cloud/storage/build/src/resumable-upload.js:574:21)
        at retry.retries ([...]/payload-gcs-credentials-test/node_modules/@google-cloud/storage/build/src/resumable-upload.js:306:29)
        at Upload.createURIAsync ([...]/payload-gcs-credentials-test/node_modules/@google-cloud/storage/build/src/resumable-upload.js:303:21)
```

**Adding a "credentials" object literal that loads its props via .env vars that are prefixed with PAYLOAD_PUBLIC_**
Like this:

```
adapter: gcsAdapter({
    options: {
      credentials: {
        type: "service_account",
        private_key: process.env.PAYLOAD_PUBLIC_GCS_PRIVATE_KEY,
        client_email: process.env.PAYLOAD_PUBLIC_GCS_CLIENT_EMAIL,
        client_id: process.env.PAYLOAD_PUBLIC_GCS_CLIENT_ID,
      },
    },
    bucket: process.env.PAYLOAD_PUBLIC_GCS_BUCKET,
}),
```

This wouldn't even be the right approach, but it's not working as well - same error as previous try

**Comment by afzaalahmad** [comment]
@arieltonglet You need to copy paste the content in string format in env variable like this:
`process.env.GCS_CREDENTIALS='// here goes your content of JSON file'`


then modify the payload config as:
```
plugins: [
    cloudStorage({
      collections: {
        media: {
          adapter: gcsAdapter({
            bucket: process.env.GCS_BUCKET,
            options: {
              credentials: JSON.parse(process.env.GCS_CREDENTIALS || "{}"),
            },
          }),
        },
      },
    }),
  ]
```

**Comment by arieltonglet** [comment]
Hi @afzaalahmad, it worked, thank you so much!
Using JSON.parse was my initial approach, but I didn't use the fallback to "{}", which was causing another error on the browser's console.

Anyway, thanks again!
