### ISSUE TITLE
Issue adding plugin with S3 adapter "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by tylandavis** [payloadcms/plugin-cloud-storage#22]
I'm running into an issue trying to add the Cloud Storage plugin with S3 adapter. I tried it with another set of S3 credentials I have used successfully in the past, so I don't believe that's causing the issue, but possible.

my `payload.config.js` file:
```
import { buildConfig } from "payload/config";
import Media from "./collections/Media";
import Users from "./collections/Users";
import { cloudStorage } from "@payloadcms/plugin-cloud-storage";
import { s3Adapter } from "@payloadcms/plugin-cloud-storage/s3";

export default buildConfig({
  collections: [Media, Users],
  plugins: [
    cloudStorage({
      collections: {
        'media': {
          adapter: s3Adapter({
            config: {
              endpoint: process.env.S3_ENDPOINT,
              credentials: {
                accessKeyId: process.env.S3_ACCESS_KEY_ID,
                secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
              },
            },
            bucket: process.env.S3_BUCKET,
          }),
        },
      },
    }),
  ],
});
```
`.env` variables:
```
S3_ENDPOINT=https://s3.amazonaws.com
S3_ACCESS_KEY_ID=*****
S3_SECRET_ACCESS_KEY=*****
S3_BUCKET=pds-detailing
```

Error log:
```
TypeError: Cannot read property 'length' of undefined
    at __spreadArray (/Users/tylan/dev/pds-detailing-backend/node_modules/@payloadcms/plugin-cloud-storage/dist/fields/getFields.js:14:66)
    at getFields (/Users/tylan/dev/pds-detailing-backend/node_modules/@payloadcms/plugin-cloud-storage/dist/fields/getFields.js:49:18)
    at /Users/tylan/dev/pds-detailing-backend/node_modules/@payloadcms/plugin-cloud-storage/dist/plugin.js:46:60
    at Array.map (<anonymous>)
    at /Users/tylan/dev/pds-detailing-backend/node_modules/@payloadcms/plugin-cloud-storage/dist/plugin.js:38:164
    at /Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/config/build.js:15:84
    at Array.reduce (<anonymous>)
    at buildConfig (/Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/config/build.js:15:50)
    at Object.<anonymous> (/Users/tylan/dev/pds-detailing-backend/payload.config.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (/Users/tylan/dev/pds-detailing-backend/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (/Users/tylan/dev/pds-detailing-backend/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at loadConfig (/Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/config/load.js:35:18)
    at init (/Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/init.js:48:41)
    at initSync (/Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/init.js:125:22)
    at Payload.init (/Users/tylan/dev/pds-detailing-backend/node_modules/payload/dist/index.js:154:29)
    at Object.<anonymous> (/Users/tylan/dev/pds-detailing-backend/server.js:13:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by FrancocDev** [comment]
I'm getting the same error!

**Comment by krthr** [comment]
Im getting the same error but with GCP adapter

**Comment by krthr** [comment]
Fixed: add `fields: [],` in your upload model:

```ts
const Media: CollectionConfig = {
	slug: "media",

	// ...

	fields: [], // <-- THIS
}
```
