### ISSUE TITLE
Error uploading file to S3: ERROR (payload): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by azivkovi** [payloadcms/plugin-cloud-storage#27]
I am using Payload CMS with `@payloadcms/plugin-cloud-storage` plugin, with Digitalocean as S3 provider.

This is my payload.config.js:

```javascript
export default buildConfig({
  collections: [Categories, Posts, Tags, Users, Media],
  plugins: [
    cloudStorage({
      collections: {
        media: {
          adapter: s3Adapter({
            config: {
              region: process.env.S3_REGION,
              endpoint: process.env.S3_ENDPOINT,
              credentials: {
                accessKeyId: process.env.S3_ACCESS_KEY_ID,
                secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
              },
            },
            bucket: process.env.S3_BUCKET,
          }),
        },
      },
    }),
  ],
  serverURL: 'http://localhost:3000',
  admin: {
    user: Users.slug,
  },
});
```

After I choose file and click save in my Media collection, I get the following in the console:

```terminal
[14:23:32] ERROR (payload): There was an error while uploading files corresponding to the collection media with filename scoring_model_idea.png:
[14:23:32] ERROR (payload): RangeError: Maximum call stack size exceeded
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:37:18)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
    at clone (C:\Users\azivkovi\dev\payload-cms\node_modules\rfdc\index.js:58:17)
```

This is my Media collection:

```javascript
const Media = {
  slug: 'media',
  admin: {
    useAsTitle: 'title',
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'alt',
      type: 'text',
      required: true,
    },
  ],
  upload: {
    staticURL: '/media',
    staticDir: 'media',
    mimeTypes: ['image/*'],
  },
};
export default Media;
```

I am having trouble debugging this problem, any help is appreciated.

**Comment by azivkovi** [comment]
As stated in another issue here, solution is to add `forcePathStyle: true` to s3Adapter config.
