### ISSUE TITLE
Region is Missing Error

### ISSUE THREAD

**Issue by dundas** [payloadcms/plugin-cloud-storage#33]
Getting the current error on s3 upload. I can't find anything in the docs about "Region" in configuration. 

```
[00:11:06] ERROR (payload): Region is missing
    Error: Region is missing
        at default (/path/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
        at /path/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
        at /path/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async coalesceProvider (/path/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
        at async /path/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
        at async useFipsEndpoint (/path/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
        at async resolveParams (/path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)
        at async getEndpointFromInstructions (/path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:7:28)
        at async /path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
[00:11:14] ERROR (payload): There was an error while uploading files corresponding to the collection media with filename Screen Shot 2023-01-14 at 6.15.24 PM-1.png:
[00:11:14] ERROR (payload): Region is missing
    Error: Region is missing
        at default (/path/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
        at /path/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
        at /path/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
[00:11:14] ERROR (payload): Region is missing
    Error: Region is missing
        at default (/path/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/config.js:10:15)
        at /path/node_modules/@aws-sdk/node-config-provider/dist-cjs/fromStatic.js:6:83
        at /path/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async coalesceProvider (/path/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
        at async /path/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:26:28
        at async useFipsEndpoint (/path/node_modules/@aws-sdk/config-resolver/dist-cjs/regionConfig/resolveRegionConfig.js:21:74)
        at async resolveParams (/path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:29:40)
        at async getEndpointFromInstructions (/path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/adaptors/getEndpointFromInstructions.js:7:28)
        at async /path/node_modules/@aws-sdk/middleware-endpoint/dist-cjs/endpointMiddleware.js:8:26
```

**Comment by tomsvogel** [comment]
hey @dundas, you could add the region to the configuration 

`  adapter: s3Adapter({
            config: {
              credentials: {
                accessKeyId: process.env.S3_ACCESS_KEY_ID,
                secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
              },
              region: process.env.S3_REGION,
            },
            bucket: process.env.S3_BUCKET,
          }),
        },`

**Comment by jmikrut** [comment]
Yes, @dundas - the above is correct. You just need to specify your region.

I will close this one out. If that didn't solve your problem, please let us know!
