### ISSUE TITLE
Error when building the app: Cannot find module '@aws-sdk/lib-storage'

### ISSUE THREAD

**Issue by imonzalvo** [payloadcms/plugin-cloud-storage#40]
Hey there! I'm having troubles when building my app. I actually had it working some weeks ago.. but I'm unable to build it now due to some errors with aws-sdk (I'm using @payloadcms/plugin-cloud-storage) the app.

This is the error I get when trying to build it:
```Error: Cannot find module '@aws-sdk/lib-storage'
Require stack:
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/index.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/s3.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/src/payload.config.ts
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/config/load.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/generateTypes.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/index.js
- /Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js:45:21)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.newLoader [as .js] (/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/handleUpload.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/dist/adapters/s3/index.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/@payloadcms/plugin-cloud-storage/s3.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/src/payload.config.ts',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/config/load.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/generateTypes.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/index.js',
    '/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/bin.js'
  ]
}
/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/build.js:35
        throw new Error(`Error: can't find the configuration file located at ${rawConfigPath}.`);
              ^

Error: Error: can't find the configuration file located at /Users/ignaciomonzalvo/projects/cms/valox-admin/src/payload.config.ts.
    at build (/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/build.js:35:15)
    at Object.<anonymous> (/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/dist/bin/index.js:16:9)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/ignaciomonzalvo/projects/cms/valox-admin/node_modules/payload/bin.js:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

Has anyone found this issue too? I actually went to my last working and I'm unable to build it now

**Comment by imonzalvo** [comment]
Workaround: Solved it be manually adding this dependency to my `package.json`.

```
    "@aws-sdk/lib-storage": "^3.267.0",
```

**Comment by itzaks** [comment]
I've experienced the same issue. Solved it by adding the dependency manually as well. I needed to add `@aws-sdk/client-s3` as well.

**Comment by jmikrut** [comment]
Hey @imonzalvo — yes, that is the fix. You need to manually install the AWS modules if you are using S3 as described in the docs. Happy you figured it out!
