### ISSUE TITLE
S3 storage adapter with local minio: Upload works, staticurl does not

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/plugin-cloud-storage#61]
```
[12:46:14] ERROR (NoSuchKey): The specified key does not exist.
    NoSuchKey: The specified key does not exist.
        at de_NoSuchKeyRes (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6070:23)
        at de_GetObjectCommandError (/app/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:4315:25)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /app/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
        at async /app/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20
        at async /app/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46
        at async /app/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:58:20
        at async /app/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```

```payload.config.ts.ts
const s3AdapterConfig: Args = {
  config: {
    credentials: {
      accessKeyId: process.env.S3_ACCESS_KEY_ID,
      secretAccessKey: process.env.S3_ACCESS_SECRET,
    },
    endpoint: process.env.S3_ENDPOINT,
    region: 'unknown',
    forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true',
  },
  bucket: process.env.S3_BUCKET,
};

    cloudStorage({
      collections: {
        downloads: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/downloads`,
        },
        images: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/images`,
        },
        videos: {
          adapter: s3Adapter(s3AdapterConfig),
          prefix: `${process.env.S3_ROOT_PATH}/videos`,
        },
      },
    }),
```

media.ts
```ts
import type { CollectionConfig } from 'payload/types';
import { createdBy } from '../../fields/created-by';
import { isAdminOrHasRole } from '../../access/is-admin-or-has-role';
import { updatedBy } from '../../fields/updated-by';

export const media: Pick<CollectionConfig, 'admin' | 'access' | 'fields'> = {
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'createdAt', 'createdBy'],
    group: 'Media',
  },
  access: {
    create: isAdminOrHasRole('media_create'),
    read: isAdminOrHasRole('media_read'),
    update: isAdminOrHasRole('media_update'),
    delete: isAdminOrHasRole('media_delete'),
  },
  fields: [
    {
      name: 'name',
      type: 'text',
      required: true,
      localized: true,
    },
    createdBy(),
    updatedBy(),
  ],
};
```
image.ts
```ts
import type { CollectionConfig } from 'payload/types';
import { media } from './media';

export const image: CollectionConfig = {
  ...media,
  slug: 'images',
  upload: {
    staticURL: '/media/images',
    adminThumbnail: 'thumbnail',
    imageSizes: [
      {
        height: 1920,
        width: 1920,
        crop: 'center',
        name: 'xlarge',
      },
      {
        height: 1536,
        width: 1536,
        crop: 'center',
        name: 'large',
      },
      {
        height: 896,
        width: 896,
        crop: 'center',
        name: 'medium',
      },
      {
        height: 448,
        width: 448,
        crop: 'center',
        name: 'small',
      },
    ],
    mimeTypes: ['image/jpeg', 'image/jpg', 'image/png'],
  },
};

```

**Comment by denolfe** [comment]
@dominikzogg I believe minio expects `us-east-1` as the region. If you set that, does it make a difference?

**Comment by dominikzogg** [comment]
@denolfe same behavior. If i only use one collection for all media it works.

**Comment by denolfe** [comment]
@dominikzogg Thank you for testing. We'll try to recreate this on our end.

**Comment by dominikzogg** [comment]
@denolfe I guess its a false alarm cause a misconfiguraiom on my side, but i haven't found it. It is my first project (migration from strapi)

**Comment by denolfe** [comment]
I tried quite a few ways to try and recreate this, but I was not able to.

**Comment by sachin-tcd** [comment]
I am having the same issue
Here is the attached image
<img width="933" alt="image" src="https://github.com/payloadcms/plugin-cloud-storage/assets/136309813/543622e7-dbc7-45fc-a8f1-aba4b91702eb">

**Comment by carlosbensant** [comment]
Same error here - PayloadCMS being recently installed.

Screenshot:
<img width="863" alt="NoSuckKey - S3" src="https://github.com/payloadcms/plugin-cloud-storage/assets/3604917/659af464-b90c-43f9-8648-a341cd56df54">

Apparently, it's checking if the file exists before creating it but it's not handling the error properly:

```
_header: 'GET /storage.dealer.do/NoSuckKey%20-%20S3.png?x-id=GetObject HTTP/1.1\r\n'
```

**Comment by denolfe** [comment]
@carlosbensant All with a similar config? Likely going to reopen and investigate if so.

**Comment by carlosbensant** [comment]
Sorry I didn't share that part but yes, similar config. I'm available if you want me to join you on a call.

**Comment by carlosbensant** [comment]
I managed to get it working by removing the `endpoint` property from the `s3Adapter` config object. If I add it back it immediately starts throwing the same error "NoSuchKey".

@denolfe Thank you for the quick reply. It motivated me to keep trying, and not give up.

**Comment by paulpopus** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud-storage) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues will be closed. This issue, however, will be transferred over.
