### ISSUE TITLE
Thumbnails won't load after uploading them in the admin dashboard (Ecommerce store)

### ISSUE THREAD

**Issue by OtaraAlex** [payloadcms/plugin-cloud-storage#89]
![Media - Payload - Google Chrome 12_11_2023 11_16_06 PM](https://github.com/payloadcms/plugin-cloud-storage/assets/111053808/fa2b25dd-9eff-4e0e-b70d-5b7d0e651b2c)

**Comment by vignesh-gupta** [comment]
@OtaraAlex  I'm facing same issue, got any solution yet?

I see some `Access denied` in error in the logs

```
[10:32:09] ERROR (payload): The specified key does not exist.
    err: {
      "type": "NoSuchKey",
      "message": "The specified key does not exist.",
      "stack":
          NoSuchKey: The specified key does not exist.
              at de_NoSuchKeyRes (E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+client-s3@3.470.0_aws-crt@1.19.0\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:6204:23)
              at de_GetObjectCommandError (E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+client-s3@3.470.0_aws-crt@1.19.0\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:4409:25)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@smithy+middleware-serde@2.0.15\node_modules\@smithy\middleware-serde\dist-cjs\deserializerMiddleware.js:7:24
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+middleware-signing@3.468.0\node_modules\@aws-sdk\middleware-signing\dist-cjs\awsAuthMiddleware.js:30:20
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@smithy+middleware-retry@2.0.24\node_modules\@smithy\middleware-retry\dist-cjs\retryMiddleware.js:31:46
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+middleware-flexible-checksums@3.468.0\node_modules\@aws-sdk\middleware-flexible-checksums\dist-cjs\flexibleChecksumsMiddleware.js:63:20
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+middleware-sdk-s3@3.470.0\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-endpoint-middleware.js:14:24
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+middleware-sdk-s3@3.470.0\node_modules\@aws-sdk\middleware-sdk-s3\dist-cjs\region-redirect-middleware.js:9:20
              at async E:\Code It\digital-marketplace\node_modules\.pnpm\@aws-sdk+middleware-logger@3.468.0\node_modules\@aws-sdk\middleware-logger\dist-cjs\loggerMiddleware.js:7:26
      "name": "NoSuchKey",
      "$fault": "client",
      "$metadata": {
        "httpStatusCode": 404,
        "requestId": "WAXRXW0A6VNDDMQ4",
        "extendedRequestId": "xelGNuS4dHz3kdkjR+HPciOlW5T4ND579VEaWqED9J076F2aomT+MHc1hc8DlPQy0RCVFRQG0R56N9SKzlap7g==",
        "attempts": 1,
        "totalRetryDelay": 0
      },
      "Code": "NoSuchKey",
      "Key": "Test Product.png",
      "RequestId": "WAXRXW0A6VNDDMQ4",
      "HostId": "xelGNuS4dHz3kdkjR+HPciOlW5T4ND579VEaWqED9J076F2aomT+MHc1hc8DlPQy0RCVFRQG0R56N9SKzlap7g=="
    }
```

**Comment by OtaraAlex** [comment]
@vignesh-gupta  I may have a solution. 
Running *yarn add @payloadcms/plugin-cloud* could temporarily solve it by upgrading the cloud plugin in the package.json file. Push the code and the images should now load after deployment.
